import {NextIntlClientProvider, hasLocale} from 'next-intl';
import {notFound} from 'next/navigation';
import {setRequestLocale} from 'next-intl/server';
import {routing} from '@/i18n/routing';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/theme/ThemeProvider";
import { headers } from "next/headers";
import "../globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

// Using Inter for monospace as well since it's a versatile font family
const interMono = Inter({
  variable: "--font-inter-mono", 
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600"], // Specific weights for monospace usage
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout(props: { children: React.ReactNode; params: Promise<{ locale: string }> }) {
  const { children } = props;
  const { locale } = await props.params;
  const headersList = await headers();
  const nonce = headersList.get("x-nonce");
  // Ensure that the incoming `locale` is valid
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  // Enable static rendering
  setRequestLocale(locale);

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${inter.variable} ${interMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
          nonce={nonce ?? undefined}
        >
          <NextIntlClientProvider>
            {children}
            <Toaster nonce={nonce ?? undefined} />
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
